---
- hosts: build-server
  become: true
  tasks:
   - name: update ubuntu
     apt:
       update_cache: yes
       cache_valid_time: 3600
   - name: Install java
     apt:
        name: openjdk-11-jre
        state: present
   - name: Download maven
     get_url:
          url: https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
          dest: /opt
   - name: Extract maven
     unarchive:
          src: /opt/apache-maven-3.9.5-bin.tar.gz
          dest: /opt
          remote_src: yes
    - name: install Docker 
      apt: 
        name: docker.io
        state: present
    - name: start docker service 
      service: 
         name: docker
         stated: started
    - name: Give 777 permision on Var 
      file:
         path: /var/run/docker.sock
         state: file 
         mode: 777
    - name: start docker serice on start 
      service:
         name: docker
         enabled: yes       